// Category এবং icon mapping — MongoDB category → card cat
const categoryMap = {
  "Senior Care": "Senior",
  "Child Care":  "Child",
  "Medical":     "Medical",
  "Support":     "Special",
  "Personal":    "Wellness",
  "Home":        "Wellness",
};

// Category based colors
const categoryStyles = {
  "Senior Care": {
    gradient: "from-blue-50 to-sky-100",
    accent: "#3b82f6",
    accentBg: "bg-blue-500",
    tagBg: "bg-blue-500",
  },
  "Child Care": {
    gradient: "from-pink-50 to-rose-100",
    accent: "#ff6fae",
    accentBg: "bg-[#ff6fae]",
    tagBg: "bg-[#ff6fae]",
  },
  "Medical": {
    gradient: "from-green-50 to-emerald-100",
    accent: "#10b981",
    accentBg: "bg-emerald-500",
    tagBg: "bg-emerald-500",
  },
  "Support": {
    gradient: "from-purple-50 to-violet-100",
    accent: "#8b5cf6",
    accentBg: "bg-violet-500",
    tagBg: "bg-violet-500",
  },
  "Personal": {
    gradient: "from-amber-50 to-yellow-100",
    accent: "#f59e0b",
    accentBg: "bg-amber-500",
    tagBg: "bg-amber-500",
  },
  "Home": {
    gradient: "from-teal-50 to-cyan-100",
    accent: "#14b8a6",
    accentBg: "bg-teal-500",
    tagBg: "bg-teal-500",
  },
};

const categoryIcons = {
  "Senior Care": "👴",
  "Child Care":  "👶",
  "Medical":     "🏥",
  "Support":     "💝",
  "Personal":    "🌟",
  "Home":        "🏡",
};

// MongoDB service → card format এ convert করো
function mapService(svc) {
  const style = categoryStyles[svc.category] || {
    gradient: "from-pink-50 to-rose-100",
    accent: "#ff6fae",
    accentBg: "bg-[#ff6fae]",
    tagBg: "bg-[#ff6fae]",
  };

  return {
    _id:       svc._id,
    title:     svc.title,
    desc:      svc.description,
    description: svc.description,
    icon:      categoryIcons[svc.category] || "✨",
    gradient:  style.gradient,
    accent:    style.accent,
    accentBg:  style.accentBg,
    tag:       svc.badge,
    tagBg:     style.tagBg,
    img:       svc.image,
    image:     svc.image,
    cat:       categoryMap[svc.category] || svc.category,
    category:  svc.category,
    price:     `$${svc.price}/hr`,
    active:    svc.active !== false,
  };
}

// API থেকে fetch করো
export async function fetchServices() {
  const serviceEndpoints = [
    "https://care-connect-server-hca5.onrender.com/services",
    "/api/services?active=true",
  ];

  let lastError = null;

  for (const endpoint of serviceEndpoints) {
    try {
      const res = await fetch(endpoint, { cache: "no-store" });

      if (!res.ok) {
        throw new Error(`Failed to fetch services from ${endpoint}`);
      }

      const data = await res.json();
      const serviceList = Array.isArray(data)
        ? data
        : Array.isArray(data?.services)
          ? data.services
          : Array.isArray(data?.data)
            ? data.data
            : Array.isArray(data?.items)
              ? data.items
              : [];

      const normalized = serviceList
        .filter((service) => service.active !== false)
        .map(mapService);

      if (normalized.length > 0) {
        return normalized;
      }
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError || new Error("Failed to fetch services");
}

// Fallback — server না চললে এগুলো দেখাবে
export const fallbackServices = [
  {
    title: "Elderly Care",
    desc: "Daily living assistance, health monitoring, and companionship for seniors.",
    description: "Daily living assistance, health monitoring, and companionship for seniors.",
    icon: "👴",
    gradient: "from-blue-50 to-sky-100",
    accent: "#3b82f6",
    accentBg: "bg-blue-500",
    tag: "Most Popular",
    tagBg: "bg-blue-500",
    img: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=600&auto=format&fit=crop&q=80",
    cat: "Senior",
    category: "Senior Care",
    price: "$15/hr",
  },
  {
    title: "Baby Sitting",
    desc: "Trusted babysitters for infants and toddlers with safety-first approach.",
    description: "Trusted babysitters for infants and toddlers with safety-first approach.",
    icon: "👶",
    gradient: "from-pink-50 to-rose-100",
    accent: "#ff6fae",
    accentBg: "bg-[#ff6fae]",
    tag: "Top Rated",
    tagBg: "bg-[#ff6fae]",
    img: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80",
    cat: "Child",
    category: "Child Care",
    price: "$12/hr",
  },
  {
    title: "Patient Care",
    desc: "In-home nursing and post-surgery recovery assistance.",
    description: "In-home nursing and post-surgery recovery assistance.",
    icon: "🏥",
    gradient: "from-green-50 to-emerald-100",
    accent: "#10b981",
    accentBg: "bg-emerald-500",
    tag: "Certified",
    tagBg: "bg-emerald-500",
    img: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80",
    cat: "Medical",
    category: "Medical",
    price: "$18/hr",
  },
  {
    title: "Special Needs",
    desc: "Tailored support for individuals with physical or developmental disabilities.",
    description: "Tailored support for individuals with physical or developmental disabilities.",
    icon: "💝",
    gradient: "from-purple-50 to-violet-100",
    accent: "#8b5cf6",
    accentBg: "bg-violet-500",
    tag: "Expert Care",
    tagBg: "bg-violet-500",
    img: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop&q=80",
    cat: "Special",
    category: "Support",
    price: "$20/hr",
  },
  {
    title: "Home Cleaning",
    desc: "Light housekeeping, laundry, and home tidying services.",
    description: "Light housekeeping, laundry, and home tidying services.",
    icon: "🧹",
    gradient: "from-pink-50 to-rose-100",
    accent: "#ff6fae",
    accentBg: "bg-[#ff6fae]",
    tag: "Convenient",
    tagBg: "bg-[#ff6fae]",
    img: "https://images.unsplash.com/photo-1581579181081-7f5f7b8d0b9f?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1581579181081-7f5f7b8d0b9f?w=600&auto=format&fit=crop&q=80",
    cat: "Home",
    category: "Home",
    price: "$12/hr",
  },
  {
    title: "Personal Care",
    desc: "Assistance with bathing, dressing and personal hygiene.",
    description: "Assistance with bathing, dressing and personal hygiene.",
    icon: "🛁",
    gradient: "from-amber-50 to-yellow-100",
    accent: "#f59e0b",
    accentBg: "bg-amber-500",
    tag: "Trusted",
    tagBg: "bg-amber-500",
    img: "https://images.unsplash.com/photo-1580281657527-6a0d5f6c9b8f?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1580281657527-6a0d5f6c9b8f?w=600&auto=format&fit=crop&q=80",
    cat: "Personal",
    category: "Personal",
    price: "$22/hr",
  },
  {
    title: "Companion Care",
    desc: "Friendly visits, conversation and social engagement for wellbeing.",
    description: "Friendly visits, conversation and social engagement for wellbeing.",
    icon: "🤝",
    gradient: "from-purple-50 to-violet-100",
    accent: "#8b5cf6",
    accentBg: "bg-violet-500",
    tag: "Caring",
    tagBg: "bg-violet-500",
    img: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=600&auto=format&fit=crop&q=80",
    cat: "Support",
    category: "Support",
    price: "$14/hr",
  },
  {
    title: "Medication Management",
    desc: "Help with medication reminders and safe administration.",
    description: "Help with medication reminders and safe administration.",
    icon: "💊",
    gradient: "from-green-50 to-emerald-100",
    accent: "#10b981",
    accentBg: "bg-emerald-500",
    tag: "Safe",
    tagBg: "bg-emerald-500",
    img: "https://images.unsplash.com/photo-1582719478179-2c7f6f3d6a8b?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1582719478179-2c7f6f3d6a8b?w=600&auto=format&fit=crop&q=80",
    cat: "Medical",
    category: "Medical",
    price: "$18/hr",
  },
  {
    title: "Post-Op Care",
    desc: "Post-surgery recovery support and wound care assistance.",
    description: "Post-surgery recovery support and wound care assistance.",
    icon: "🩺",
    gradient: "from-teal-50 to-cyan-100",
    accent: "#14b8a6",
    accentBg: "bg-teal-500",
    tag: "Professional",
    tagBg: "bg-teal-500",
    img: "https://images.unsplash.com/photo-1580281657527-1a2b3c4d5e6f?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1580281657527-1a2b3c4d5e6f?w=600&auto=format&fit=crop&q=80",
    cat: "Medical",
    category: "Medical",
    price: "$28/hr",
  },
  {
    title: "Respite Care",
    desc: "Temporary relief for primary caregivers through trusted cover.",
    description: "Temporary relief for primary caregivers through trusted cover.",
    icon: "⏸️",
    gradient: "from-indigo-50 to-blue-100",
    accent: "#6366f1",
    accentBg: "bg-indigo-500",
    tag: "Relief",
    tagBg: "bg-indigo-500",
    img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80",
    cat: "Support",
    category: "Support",
    price: "$16/hr",
  },
  {
    title: "Hospice Support",
    desc: "Comfort-focused end-of-life care with a compassionate team.",
    description: "Comfort-focused end-of-life care with a compassionate team.",
    icon: "🕊️",
    gradient: "from-sky-50 to-blue-100",
    accent: "#0ea5e9",
    accentBg: "bg-sky-500",
    tag: "Compassion",
    tagBg: "bg-sky-500",
    img: "https://images.unsplash.com/photo-1508997449629-303059a039d3?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1508997449629-303059a039d3?w=600&auto=format&fit=crop&q=80",
    cat: "Medical",
    category: "Medical",
    price: "$30/hr",
  },
  {
    title: "Live-in Care",
    desc: "Full-time live-in caregivers for continuous support at home.",
    description: "Full-time live-in caregivers for continuous support at home.",
    icon: "🏠",
    gradient: "from-blue-50 to-sky-100",
    accent: "#3b82f6",
    accentBg: "bg-blue-500",
    tag: "24/7",
    tagBg: "bg-blue-500",
    img: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&auto=format&fit=crop&q=80",
    cat: "Home",
    category: "Home",
    price: "$200/day",
  },
  {
    title: "Child Care",
    desc: "After-school supervision, homework help, and activity coordination.",
    description: "After-school supervision, homework help, and activity coordination.",
    icon: "🧒",
    gradient: "from-amber-50 to-yellow-100",
    accent: "#f59e0b",
    accentBg: "bg-amber-500",
    tag: "New",
    tagBg: "bg-amber-500",
    img: "https://images.unsplash.com/photo-1484820540052-0182ef970858?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1484820540052-0182ef970858?w=600&auto=format&fit=crop&q=80",
    cat: "Child",
    category: "Child Care",
    price: "$11/hr",
  },
  {
    title: "Night Care",
    desc: "Overnight supervision and monitoring for safety and comfort.",
    description: "Overnight supervision and monitoring for safety and comfort.",
    icon: "🌙",
    gradient: "from-indigo-50 to-blue-100",
    accent: "#6366f1",
    accentBg: "bg-indigo-500",
    tag: "24/7",
    tagBg: "bg-indigo-500",
    img: "https://images.unsplash.com/photo-1493894473891-10fc1e5dbd22?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1493894473891-10fc1e5dbd22?w=600&auto=format&fit=crop&q=80",
    cat: "Senior",
    category: "Senior Care",
    price: "$20/hr",
  },
  {
    title: "Therapy Support",
    desc: "In-home physical and occupational therapy assistance.",
    description: "In-home physical and occupational therapy assistance.",
    icon: "🧘",
    gradient: "from-teal-50 to-cyan-100",
    accent: "#14b8a6",
    accentBg: "bg-teal-500",
    tag: "Professional",
    tagBg: "bg-teal-500",
    img: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80",
    cat: "Medical",
    category: "Medical",
    price: "$22/hr",
  },
  {
    title: "Dementia Care",
    desc: "Specialized memory care with structured routines and cognitive engagement.",
    description: "Specialized memory care with structured routines and cognitive engagement.",
    icon: "🧠",
    gradient: "from-sky-50 to-blue-100",
    accent: "#0ea5e9",
    accentBg: "bg-sky-500",
    tag: "Specialist",
    tagBg: "bg-sky-500",
    img: "https://images.unsplash.com/photo-1581595219315-a187dd40c322?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1581595219315-a187dd40c322?w=600&auto=format&fit=crop&q=80",
    cat: "Senior",
    category: "Senior Care",
    price: "$20/hr",
  },
  {
    title: "Newborn Care",
    desc: "Expert care for newborns - feeding schedules, sleep training, and hygiene.",
    description: "Expert care for newborns - feeding schedules, sleep training, and hygiene.",
    icon: "🍼",
    gradient: "from-pink-50 to-fuchsia-100",
    accent: "#d946ef",
    accentBg: "bg-fuchsia-500",
    tag: "Specialist",
    tagBg: "bg-fuchsia-500",
    img: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80",
    cat: "Child",
    category: "Child Care",
    price: "$15/hr",
  },
  {
    title: "Disability Care",
    desc: "Assistance for adults with physical disabilities, promoting independence.",
    description: "Assistance for adults with physical disabilities, promoting independence.",
    icon: "♿",
    gradient: "from-lime-50 to-green-100",
    accent: "#84cc16",
    accentBg: "bg-lime-500",
    tag: "Accessible",
    tagBg: "bg-lime-500",
    img: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&auto=format&fit=crop&q=80",
    cat: "Special",
    category: "Support",
    price: "$17/hr",
  },
  {
    title: "Autism Support",
    desc: "Structured routines and behavioral support for children with ASD.",
    description: "Structured routines and behavioral support for children with ASD.",
    icon: "🌈",
    gradient: "from-violet-50 to-purple-100",
    accent: "#a855f7",
    accentBg: "bg-purple-500",
    tag: "ASD Certified",
    tagBg: "bg-purple-500",
    img: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&auto=format&fit=crop&q=80",
    cat: "Special",
    category: "Support",
    price: "$18/hr",
  },
  {
    title: "Nutrition Care",
    desc: "Meal preparation and dietary management for specific health conditions.",
    description: "Meal preparation and dietary management for specific health conditions.",
    icon: "🥗",
    gradient: "from-green-50 to-lime-100",
    accent: "#22c55e",
    accentBg: "bg-green-500",
    tag: "Healthy",
    tagBg: "bg-green-500",
    img: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&auto=format&fit=crop&q=80",
    cat: "Wellness",
    category: "Personal",
    price: "$13/hr",
  },
  {
    title: "School Support",
    desc: "Homework help, exam preparation, and learning disability accommodations.",
    description: "Homework help, exam preparation, and learning disability accommodations.",
    icon: "📚",
    gradient: "from-sky-50 to-indigo-100",
    accent: "#4f46e5",
    accentBg: "bg-indigo-600",
    tag: "Academic",
    tagBg: "bg-indigo-600",
    img: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
    cat: "Child",
    category: "Child Care",
    price: "$12/hr",
  },
];